apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: apr8-objdet
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/apr8-objdet:04c589249ec141590bf3bca2c8827bd8db816c85@sha256:a4c7442598f30ce4ad9556dc7f49cb49772f5d5ed5833aa522d2c13a8d340547 # use pre-built to bootstrap
          name: app-inference
