apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: apr8-objdet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr8-objdet
  name: apr8-objdet
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
